# Generated by Django 4.2.4 on 2023-12-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
